" Edit another file in the same directory as the current file
" uses expression to extract path from current file's path
" (thanks Douglas Potts)
if has("unix")
  map ,e :e <C-R>=expand("%:p:h") . '/'<CR>
else
  map ,e :e <C-R>=expand("%:p:h") . '\'<CR>
endif

" expend tab
set et
" line number
set nu
" auto indent
set autoindent
set smartindent
set cindent
set cinoptions=g0

" Highly recommended to set tab keys to 2 spaces
set tabstop=2
set shiftwidth=2

" Lines with equal indent form a fold
" set foldmethod=indent

" set cindent
" set cinkeys=0{,0},!^F,o,O,e " default is: 0{,0},0),:,0#,!^F,o,O,e
filetype plugin indent on

filetype plugin on

let g:C_MapLeader = ','

syntax enable

set ignorecase
set smartcase

source $HOME/.vim/vimrc_encoding      " Encoding

" set enc=utf8 gfn=Courier_New:h12:w7 fencs=ucs-bom,utf8,chinese
" set gfw=NSimSun-18030,GulimChe,GungsuhChe,FangSong,MS_Mincho,SimHei

" inoremap <tab> <c-p>

:set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
:set laststatus=2

nmap <F8> :TagbarToggle<CR>
